### ISSUE TITLE
Transmitting at high freq: bug in line merging

### ISSUE THREAD

**Issue by f4hzg** [ceyzeriat/hein#1]
There seems to be a bug when sending large amount of data at high frequency using a socTransmitter.

Just try out the following code, and you'll see that it works for a while, and then transmission just stops.

`import hein
import time

SEND_FREQ = 500 # in Hz

t = hein.SocTransmitter(port = 60000, nreceivermax=1, start = True, portname = "port")
r = hein.SocReceiver(port = 60000, name = "name", connect = True, hostname = "localhost", portname="port")

while(True):
    t.tell_raw("a"*200)
    time.sleep(1/SEND_FREQ)`

I have traced the error down to line 309 of the file hein/soctransmitter.py, which reads:
`new_lines_to_send = [[lines_to_send[0], lines_to_send[1], 1]]`

If I understand the code correctly, I think it should be:
`new_lines_to_send = [[lines_to_send[0][0], lines_to_send[0][1], 1]]`
which indeed seems to fix the issue.

**Comment by ceyzeriat** [comment]
You are absolutely right. Thanks for your careful eye and debugging!
I actually saw this bug a few weeks ago but did not take the time to look at it in detail as it was the first time it appeared - I thought it might have been a ghost in the shell.
Amazing how this bug made it through all the way!
